esphome:
 # name: solarHotwaterControl
  name: esphome-web-43242b
  friendly_name: 太阳能控制器
  includes:
    - solarhotwatercontrol.h
  on_boot:
    - priority: 800                      # This is where all hardware initialization of vital components is executed
      then:
        - lambda: |-
            setTimestamps();

esp8266:
  board: esp01_1m
  restore_from_flash: True
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "solarHotWater Fallback Hotspot"
    password: ""
 
logger:
  level: DEBUG
captive_portal:
api:
ota:
web_server:
  port: 80

time:
  - platform: sntp
    id: sntp_time
    timezone: Asia/Shanghai
    on_time:
      - seconds: 0
        minutes: 0
        hours: 0
        then:
          - lambda: |-
              setTimestamps();

sun:
  id: mysun
  latitude: 30.291575  #纬度
  longitude: 120.053896 #经度


interval:
  - interval: 10s
    then:
      - lambda: |-
          onInterval();

globals:
  - id: global_timer
    type: uint8_t[20][17]
    restore_value: yes # switch to yes for deployment
  - id: global_last_run
    type: time_t[20]
    restore_value: yes # switch to yes for deployment
  - id: global_next_run
    type: time_t[20]
    restore_value: no
  - id: flag_count_antifreezSolar
    type: bool
    restore_value: yes
    initial_value : "false"
  - id: flag_count_antifreezPipe
    type: bool
    restore_value: yes
    initial_value : "false"


# /***************************************************
# *      ***** Timer Format Cheat Guide *****
# * **************************************************
# *              ***** Switches *****
# *   *** Value set to '1' enabled '0' disabled ***
# * 0 = Enabled
# * 1-7 = Days (sun-sat)
# * 8 = Repeat
# * 9 = Negative Offset
# *               ***** Numbers *****
# * 10 = Time hour
# * 11 = Time minute
# * 12 = Output  {value '0' for the first position of switch in the 'relays' variable}
# * 13 = Action  {'0' turn off, '1' turn on, '2' toggle}
# * 14 = Offset hour
# * 15 = Offset minute
# * 16 = Mode    {'0' use time, '1' use sunrise, '2' use sunset} 
# ****************************************************/

number:
  - platform: template
    name: "83 Timer Time Hour"
    id: time_hour
    optimistic: true
    restore_value: false
    min_value: 0
    max_value: 23
    step: 1
    unit_of_measurement: Hours
    mode: box
  - platform: template
    name: "84 Timer Time Minute"
    id: time_minute
    optimistic: true
    restore_value: false
    min_value: 0
    max_value: 59
    step: 1
    unit_of_measurement: Minutes
    mode: box
  - platform: template
    name: "93 Timer Output"
    id: output
    optimistic: true
    restore_value: false
    initial_value: 0
    min_value: 0
    max_value: 1
    step: 1
    unit_of_measurement: Relay Position
    mode: box
  - platform: template
    name: "94 Timer Action"
    id: action
    optimistic: true
    restore_value: false
    min_value: 0
    max_value: 2
    step: 1
    mode: box
  - platform: template
    name: "95 Timer Offset Hour"
    id: offset_hour
    optimistic: true
    restore_value: false
    min_value: 0
    max_value: 11
    step: 1
    unit_of_measurement: Hours
    mode: box
  - platform: template
    name: "96 Timer Offset Minute"
    id: offset_minute
    optimistic: true
    restore_value: false
    min_value: 0
    max_value: 59
    step: 1
    unit_of_measurement: Minutes
    mode: box
  - platform: template
    name: "98 Timer Mode"
    id: mode
    optimistic: true
    restore_value: false
    min_value: 0
    max_value: 2
    step: 1
    mode: box

#add by zhou start
  - platform: template
    name: 101 Tank Target Temperature
    id: target_temp
    optimistic: true
    restore_value: true
    initial_value: 50
    min_value: 1
    max_value: 70
    unit_of_measurement: °C
    step: 1
    mode: box
#add by zhou end    


switch:
  - platform: gpio
    name: Heater
    id: relay_0_heater
    pin: GPIO16   #  改相应针
    inverted: false
    restore_mode: RESTORE_DEFAULT_OFF
  # - platform: gpio
  #   name: Relay 1
  #   id: relay_1
  #   pin: 4
  #   inverted: false
  #   restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    name: Pump1  #太阳能板循环泵
    id: pump1
    pin: GPIO4    #  改相应针
    inverted: false
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    name: Pump2  #管道热水循环泵
    id: pump2
    pin: GPIO5    #  改相应针
    inverted: false
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: template
    name: 103 Holiday
    id: holiday_mode
    optimistic : true
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: template
    name: 82 Timer Enabled
    id: enabled
    optimistic : true
    restore_mode: ALWAYS_OFF

  - platform: template
    name: 86 Timer Sunday
    id: sunday
    optimistic : true
    restore_mode: ALWAYS_OFF
  - platform: template
    name: 87 Timer Monday
    id: monday
    optimistic : true
    restore_mode: ALWAYS_OFF
  - platform: template
    name: 88 Timer Tuesday
    id: tuesday
    optimistic : true
    restore_mode: ALWAYS_OFF
  - platform: template
    name: 89 Timer Wednesday
    id: wednesday
    optimistic : true
    restore_mode: ALWAYS_OFF
  - platform: template
    name: 90 Timer Thursday
    id: thursday
    optimistic : true
    restore_mode: ALWAYS_OFF
  - platform: template
    name: 91 Timer Friday
    id: friday
    optimistic : true
    restore_mode: ALWAYS_OFF
  - platform: template
    name: 92 Timer Saturday
    id: saturday
    optimistic : true
    restore_mode: ALWAYS_OFF

  - platform: template
    name: 85 Timer Repeat
    id: repeat
    optimistic : true
    restore_mode: ALWAYS_OFF
  - platform: template
    name: 97 Timer Negative Offset
    id: negative_offset
    optimistic : true
    restore_mode: ALWAYS_OFF

  - platform: template
    name: 99 Timer Override
    id: override_timer
    optimistic : true
    restore_mode: ALWAYS_OFF



select:
  - platform: template
    id: select_timer
    name: "80 Timer Select"
    optimistic : true
    restore_value: false
    initial_option: -- Select --
    options: 
      - -- Select --
      - Timer 1 HeaterOn
      - Timer 2 HeaterOff
      - Timer 3 HeaterOn
      - Timer 4 HeaterOff
      - Timer 5 HeaterOn
      - Timer 6 HeaterOff
      # - Timer 7
      # - Timer 8
      # - Timer 9
      # - Timer 10
      # - Timer 11
      # - Timer 12
      # - Timer 13
      # - Timer 14
      # - Timer 15
      # - Timer 16
      # - Timer 17
      # - Timer 18
      # - Timer 19
      # - Timer 20
    on_value:
      - lambda: |-
          onSelect(x);

button:
  - platform: template
    name: 81 Timer Save
    on_press:
      - lambda: |-
          onPressSave();
  - platform: template
    name: 102 Hotwater Manual Heating
    on_press: 
    #水箱加热至目标温度
      - lambda: |-
          onPressHeatingtoTarget();
    
        
  - platform: restart
    name: "Restart"
# DS18B20温度传感器
dallas:
  - pin: GPIO2 
    update_interval: 10s
sensor:
  - platform: dallas
    address: 0x140000003089bc28
    name: "t1_solar"
#    name: "太阳能板处温度"
    id: t1_solar
    
  - platform: dallas
    address: 0xe200000031ace028
    name: "t2_tank_top"
#    name: "热水箱上部温度"
    id: t2_tank_top
  - platform: dallas
    address: 0xc0000000335cd228
    name: "t3_pipe"
#    name: "循环水管处温度"
    id: t3_pipe
  - platform: dallas
    address: 0x9a00000031399728
    name: "t4_tank_bottom"
#    name: "热水箱下部温度"
    id: t4_tank_bottom  

  - platform: wifi_signal
    name:  solarHotwaterControl WiFi Signal
    update_interval: 60s
text_sensor:
  - platform: wifi_info
    ip_address:
      name: solarHotwaterControl IP Address    
    